name: jjinternational
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  cloud_firestore: ^5.1.0
  firebase_core: ^3.2.0
  flutter:
    sdk: flutter
  go_router: ^14.2.1
  infinite_carousel: ^1.1.1
  provider: ^6.1.2
  flutter_web_plugins:
    sdk: flutter 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/products/
    - assets/certificates/
    - assets/carosuel/
    - assets/profile/
